//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMPad.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseSystemLanguage {
            get {
                return ((bool)(this["UseSystemLanguage"]));
            }
            set {
                this["UseSystemLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int RecentFilesMax {
            get {
                return ((int)(this["RecentFilesMax"]));
            }
            set {
                this["RecentFilesMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _empath {
            get {
                return ((string)(this["_empath"]));
            }
            set {
                this["_empath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _runROM {
            get {
                return ((bool)(this["_runROM"]));
            }
            set {
                this["_runROM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _runROMspr {
            get {
                return ((bool)(this["_runROMspr"]));
            }
            set {
                this["_runROMspr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _backupIPS {
            get {
                return ((bool)(this["_backupIPS"]));
            }
            set {
                this["_backupIPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _backupOne {
            get {
                return ((bool)(this["_backupOne"]));
            }
            set {
                this["_backupOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public decimal rfiles {
            get {
                return ((decimal)(this["rfiles"]));
            }
            set {
                this["rfiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool autocomp {
            get {
                return ((bool)(this["autocomp"]));
            }
            set {
                this["autocomp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"rtl adc and asl bcc blt bcs bge beq bit bmi bne bpl bra brk brl bvc bvs clc cld cli clv cmp cop cpx cpy dec dex dey eor inc inx iny jml jmp jsl jsr lda ldx ldy lsr mvn mvp nop ora pea pei per pha phb phd phk php phx phy pla plb pld plp plx ply rep rol ror rti rts sbc sec sed sei sep sta stp stx sty stz tax tay tcd tcs tdc trb tsb tsc tsx txa txs txy tya tyx wai wdm xba xce")]
        public string _opcodes {
            get {
                return ((string)(this["_opcodes"]));
            }
            set {
                this["_opcodes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("header lorom org db pc dcb \"\"star\"\" + - ++ -- +++ --- star start end dw incbin in" +
            "csrc print macro endmacro")]
        public string _misc {
            get {
                return ((string)(this["_misc"]));
            }
            set {
                this["_misc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 128, 255")]
        public global::System.Drawing.Color opcodeclr {
            get {
                return ((global::System.Drawing.Color)(this["opcodeclr"]));
            }
            set {
                this["opcodeclr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 0, 192")]
        public global::System.Drawing.Color addclr {
            get {
                return ((global::System.Drawing.Color)(this["addclr"]));
            }
            set {
                this["addclr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color commentclr {
            get {
                return ((global::System.Drawing.Color)(this["commentclr"]));
            }
            set {
                this["commentclr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 192")]
        public global::System.Drawing.Color keywordclr {
            get {
                return ((global::System.Drawing.Color)(this["keywordclr"]));
            }
            set {
                this["keywordclr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool loaddefs {
            get {
                return ((bool)(this["loaddefs"]));
            }
            set {
                this["loaddefs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1117, 562")]
        public global::System.Drawing.Size MySize {
            get {
                return ((global::System.Drawing.Size)(this["MySize"]));
            }
            set {
                this["MySize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MyLoc {
            get {
                return ((global::System.Drawing.Point)(this["MyLoc"]));
            }
            set {
                this["MyLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState MyState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["MyState"]));
            }
            set {
                this["MyState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hel {
            get {
                return ((bool)(this["hel"]));
            }
            set {
                this["hel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hal {
            get {
                return ((bool)(this["hal"]));
            }
            set {
                this["hal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool whitespace {
            get {
                return ((bool)(this["whitespace"]));
            }
            set {
                this["whitespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkTurquoise")]
        public global::System.Drawing.Color whitespacecol {
            get {
                return ((global::System.Drawing.Color)(this["whitespacecol"]));
            }
            set {
                this["whitespacecol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool defboth {
            get {
                return ((bool)(this["defboth"]));
            }
            set {
                this["defboth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool loadfile {
            get {
                return ((bool)(this["loadfile"]));
            }
            set {
                this["loadfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ActiveCaptionText")]
        public global::System.Drawing.Color cursorcol {
            get {
                return ((global::System.Drawing.Color)(this["cursorcol"]));
            }
            set {
                this["cursorcol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OldLace")]
        public global::System.Drawing.Color halcol {
            get {
                return ((global::System.Drawing.Color)(this["halcol"]));
            }
            set {
                this["halcol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentFiles"]));
            }
            set {
                this["RecentFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string debugpath {
            get {
                return ((string)(this["debugpath"]));
            }
            set {
                this["debugpath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("102, 104, 105")]
        public global::System.Drawing.Color labclr {
            get {
                return ((global::System.Drawing.Color)(this["labclr"]));
            }
            set {
                this["labclr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boldlab {
            get {
                return ((bool)(this["boldlab"]));
            }
            set {
                this["boldlab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color selbackcl {
            get {
                return ((global::System.Drawing.Color)(this["selbackcl"]));
            }
            set {
                this["selbackcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 224, 224")]
        public global::System.Drawing.Color selforcl {
            get {
                return ((global::System.Drawing.Color)(this["selforcl"]));
            }
            set {
                this["selforcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int MarginWidth {
            get {
                return ((int)(this["MarginWidth"]));
            }
            set {
                this["MarginWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showidentguides {
            get {
                return ((bool)(this["showidentguides"]));
            }
            set {
                this["showidentguides"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public decimal tabwidth {
            get {
                return ((decimal)(this["tabwidth"]));
            }
            set {
                this["tabwidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool smartindent {
            get {
                return ((bool)(this["smartindent"]));
            }
            set {
                this["smartindent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hl {
            get {
                return ((bool)(this["hl"]));
            }
            set {
                this["hl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkOrchid")]
        public global::System.Drawing.Color ok {
            get {
                return ((global::System.Drawing.Color)(this["ok"]));
            }
            set {
                this["ok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("b l w a x y")]
        public string okkey {
            get {
                return ((string)(this["okkey"]));
            }
            set {
                this["okkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool calltips {
            get {
                return ((bool)(this["calltips"]));
            }
            set {
                this["calltips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boldop {
            get {
                return ((bool)(this["boldop"]));
            }
            set {
                this["boldop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boldaddr {
            get {
                return ((bool)(this["boldaddr"]));
            }
            set {
                this["boldaddr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boldcom {
            get {
                return ((bool)(this["boldcom"]));
            }
            set {
                this["boldcom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boldkey {
            get {
                return ((bool)(this["boldkey"]));
            }
            set {
                this["boldkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boldok {
            get {
                return ((bool)(this["boldok"]));
            }
            set {
                this["boldok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool regd {
            get {
                return ((bool)(this["regd"]));
            }
            set {
                this["regd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lucida Console, 9.75pt")]
        public global::System.Drawing.Font font {
            get {
                return ((global::System.Drawing.Font)(this["font"]));
            }
            set {
                this["font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CommentItal {
            get {
                return ((bool)(this["CommentItal"]));
            }
            set {
                this["CommentItal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("File = $010A\r\nPowerup = $19\r\nPlayer = $0DB3\r\nImageLoader = $12\r\nFrameA = $13\r\nFra" +
            "meB = $14\r\nLives = $0DBE\r\nPose = $13E0\r\nControllerData15 = $15\r\nControllerData16" +
            " = $16\r\nControllerData17 = $17\r\nControllerData18 = $18\r\nLayer1X = $1A\r\nLayer1Y =" +
            " $1C\r\nLayer2X = $1E\r\nLayer2Y = $20\r\nLayer3X = $22\r\nLayer3Y = $24\r\nMode7CenterX =" +
            " $2A\r\nMode7CenterY = $2C\r\nMode7ParaA = $2E\r\nMode7ParaB = $30\r\nMode7ParaC = $32\r\n" +
            "Mode7ParaD = $34\r\nMode7Rot = $36\r\nMode7Scale = $38\r\nMode7Layer1X = $3A\r\nMode7Lay" +
            "er1Y = $3C\r\nScreensInLevel = $5D\r\nSprProp = $64\r\nMarioDir = $76\r\nInWater = $75\r\n" +
            "IsClimbing = $74\r\nIsDucking = $73\r\nImageInAir = $72\r\nObscureMario = $78\r\nMarioXS" +
            "p = $7B\r\nMarioYSp = $7D\r\nMarioXPos = $7E\r\nMarioYPos = $80\r\nIsWaterLevel = $85\r\nA" +
            "nimation = $71\r\nMarioXPosNext = $94\r\nMarioYPosNext = $96\r\nSpriteNum = $9E\r\nCusto" +
            "mSprNum = $7FAB9E\r\nSprXSp = $B6\r\nSprYSp = $AA\r\nMarioXPosCur = $D1\r\nMarioYPosCur " +
            "= $D3\r\nGameMode = $0100\r\nStack = $010B\r\nTwoPlayerFlag = $0DB2\r\nItemBox = $0DC2\r\n" +
            "MarioXPosOW = $1F17\r\nMarioYPosOW = $1F19\r\nMarioScore = $0F34\r\nLuigiScore = $0F37" +
            "\r\nBonusStars = $0F48\r\nTransLevelNum = $13BF\r\nCurOWTile = $13C1\r\nYoshiCol = $13C7" +
            "\r\nMidwayFlag = $13CE\r\nPause = $13D4\r\nCapeImg = $13DF\r\nSpinJump = $140D\r\nMsgBox =" +
            " $1426\r\nKeyHoleXPos = $1436\r\nKeyHoleYPos = $1438\r\nDeathMsg = $143B\r\nCarryFlag = " +
            "$1470\r\nHoldFlag = $148F\r\nLvlEndTimer = $1493\r\nMarioHurtTimer = $1496\r\nMarioInvTi" +
            "mer = $1497\r\nCapeSpinTimer = $14A6\r\nBluePOW = $14AD\r\nSilverPOW = $14AE\r\nOnOff = " +
            "$14AF\r\nSprStat = $14C8\r\nSprXPosHi = $14E0\r\nSprYPosHi = $14D4\r\nSprXPosLo = $E4\r\nS" +
            "prYPosLo = $D8\r\nShakeGroundTimer = $1887\r\nBalloonTimer = $1891\r\nRidingYoshi = $1" +
            "87A\r\nRedBerry = $18D4\r\nPinkBerry = $18D5\r\nSilverCoins = $18DD\r\nSprLocked = $9D\r\n" +
            "ExtSpr = $170B\r\nSmokeImg = $17C0\r\nSmokeXPosLo = $17C4\r\nSmokeYPosLo = $17C8\r\nIsSl" +
            "ippery = $86")]
        public string listdef {
            get {
                return ((string)(this["listdef"]));
            }
            set {
                this["listdef"] = value;
            }
        }
    }
}
